### ISSUE TITLE
npm rebuild error

### ISSUE THREAD

**Issue by DavidD303** [gberg927/MMM-DisneyWaitTimes#20]
I was rebuilding my magic mirror with a fresh install and when installing this module got the following error

Error: Could not detect abi for version 11.3.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/node-abi/index.js:30:9)
    at new Rebuilder (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:126:48)
    at rebuildWithOptions (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:404:23)
    at Object.doRebuild [as rebuild] (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:427:16)
    at /home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/cli.js:124:33
    at Generator.next (<anonymous>)
    at fulfilled (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/cli.js:6:58)

**Comment by gberg927** [comment]
Fixed in #21 
Please grab the latest code and try again. Let me know if that works for you.
`git pull origin master`

**Comment by DavidD303** [comment]
that fixed it thank you!
