### ISSUE TITLE
Rebuild Failure

### ISSUE THREAD

**Issue by DavidD303** [gberg927/MMM-DisneyWaitTimes#26]
pi@magicmirror:~/MagicMirror/modules/MMM-DisneyWaitTimes $ npm run rebuild

> MMM-DisneyWaitTimes@1.1.0 rebuild /home/pi/MagicMirror/modules/MMM-DisneyWaitTimes
> electron-rebuild

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
Could not detect abi for version 16.0.5 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 16.0.5 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at Object.getAbi (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/node-abi/index.js:36:9)
    at Rebuilder.get ABI [as ABI] (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:111:39)
    at ModuleRebuilder.prebuildNativeModuleExists (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/module-rebuilder.js:129:146)
    at Rebuilder.rebuildModuleAt (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:170:35)
    at async Rebuilder.rebuild (/home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/rebuild.js:152:17)
    at async /home/pi/MagicMirror/modules/MMM-DisneyWaitTimes/node_modules/electron-rebuild/lib/src/cli.js:146:9
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! MMM-DisneyWaitTimes@1.1.0 rebuild: `electron-rebuild`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the MMM-DisneyWaitTimes@1.1.0 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2022-03-06T22_06_39_151Z-debug.log

**Comment by DavidD303** [comment]
I already tried the "git pull origin master" which fixed this issue previously

**Comment by gberg927** [comment]
I removed the dependency that was creating the need to do the rebuild step. Try pulling the latest code. Please note you do not need to do `npm run rebuild` anymore
